defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount
  - loss: pixelwiseloss
  - augmentation: no_aug
  - training: hourglass
  - hydra: standard

gpus: [0]
debug: false
root_dir: /home/gscarpellini/dev
model_zoo: /data/gscarpellini/model_zoo
resume: false
load_path:
result_file: aucs.json 
