defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount_pose
  - loss: pixelwiseloss
  - augmentation: center_crop
  - training: reconstruction
  - hydra: standard

gpus: [0]
debug: false
root_dir: /home/gianscarpe/dev

resume: false
load_path: 
