defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount
  - loss: pixelwiseloss
  - augmentation: center_crop
  - training: hourglass
  - hydra: standard

gpus: [0]
debug: false
root_dir: /home/gianscarpe/dev
model_zoo: /data/gscarpellini/model_zoo
resume: false
load_path:
