defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount_pose
  - loss: pixelwiseloss
  - augmentation: no_aug
  - training: hourglass
  - hydra: standard

gpus: [0]
debug: false
root_dir: /home/gianscarpe/dev
model_zoo: /data/gscarpellini/model-zoo
resume: false
load_path: 
