language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install .
# command to run tests
script:
  "python -m unittest discover tests"

after_success:
    coveralls
