name: gianscarpe-master-thesis
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - albumentations
  - cudatoolkit=10.2
  - h5py
  - hdf5
  - python=3.7.7
  - scikit-image
  - scikit-learn
  - scikit-video
  - scipy
  - pytorch=1.4.0
  - kornia
  - pip:
    - hydra-core==1.0.0rc1
    - numpy
    - omegaconf
    - opencv-python
    - pytorch-lightning==0.8.5
    - tensorboard
    - torchvision==0.5.0
    - tqdm


