training:
  epochs: 100
  early_stopping: 10
  batch_size: 32
  num_workers: 12
  use_lr_scheduler: false
  module: HourglassEstimator
  model: HourglassModel
  backbone: classification/resnet34.pt
  stages: 2  
