training:
  epochs: 100
  early_stopping: 10
  batch_size: 32
  num_workers: 12
  module: MargiposeEstimator
  model: MargiPoseModel
  backbone:
    timecount/classification/resnet34.pt
  stages: 2
  predict_3d: true
