 training:
  epochs: 100
  early_stopping: 10
  batch_size: 32
  num_workers: 12
  module: MargiposeEstimator
  model: resnet34
  backbone: timecount/classification/resnet34.pt
  latent_size: 256
  stages: 2
  predict_3d: true
  pretrained: true
