defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount
  - loss: pixelwiseloss
  - augmentation: no_aug
  - training: margipose
  - hydra: standard
  - hydra/help: help

gpus: [0]
epochs: 100
early_stopping: 10
batch_size: 64
num_workers: 12
debug: false
root_dir: /home/gianscarpe/dev
model_zoo: /data/gscarpellini/model_zoo
project_name: event_hpe
resume: false
load_path:
result_file: aucs.json 
accelerator: 'ddp'
