defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount
  - loss: crossentropy
  - augmentation: center_crop
  - training: classification
  - hydra: standard

debug: false
root_dir: /home/gianscarpe/dev
