defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  - dataset: timecount_pose
  - loss: heatmap
  - augmentation: no_aug
  - training: reconstruction
  - hydra: standard

gpus: [1]
debug: false
root_dir: /home/gianscarpe/dev

resume: false
load_path: 
