defaults:
  - optimizer: adam
  - dataset: timecount
  - loss: crossentropy
  - augmentation: center_crop
  - training: standard

loading: false
debug: false
model: resnet34
root_dir: /home/gianscarpe/dev

hydra:
  sweep:
    dir: ${root_dir}/exps/${dataset.name}/exp${now:%m-%d}
    subdir: exp_${hydra.job.num}_${now:%H-%M-%S}
  run:
    dir: ${root_dir}/exps/${dataset.name}/exp${now:%m-%d}/exp_${now:%H-%M-%S}
      

