defaults:
  - representation: voxel
  - vid2e: standard

show_debug_images: 10
input_dir: /home/gscarpellini/test
output_dir: /home/gscarpellini/dev/event-camera/data
batch_size: 1
extract: false    
